spring:
    data:
        mongodb:
            database: chatbot_db
    main:
        web-application-type: NONE

logging:
    level:
        com:
            github:
                lobakov:
                    chatbot: DEBUG 
        org:
            springframework:
                boot: DEBUG
